# Generated by Django 4.2.5 on 2023-09-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="room", old_name="name", new_name="names",),
    ]
